// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwrisjdptnwdkwdnmbzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3cmlzamRwdG53ZGt3ZG5tYnp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4Mzc4NDEsImV4cCI6MjA2NTQxMzg0MX0.AHYIx8kacodwwi-9FZGWOfy4Bdxrl5Gg2O5m8LoI9L8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);